import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CloudStore} from '../src/cloud-store.js';
import {fresh,hatch,lesson,equip,travel} from '../src/game.js';
import {validateSave,parseBackup,backupText} from '../src/save-validation.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
function backend(){let row=null;const receipts=new Map();let history=[];return {read:async()=>structuredClone(row),history:async()=>structuredClone(history),commit:async p=>{if(receipts.has(p.p_operation_id))return structuredClone(row);if((row?.revision||0)!==p.p_expected_revision)throw Object.assign(Error('conflict'),{code:'PT409'});row={state:validateSave(p.p_state),revision:(row?.revision||0)+1,updated_at:new Date().toISOString()};receipts.set(p.p_operation_id,row.revision);history=[structuredClone(row),...history].slice(0,20);return structuredClone(row);}};}
async function store(api=backend(),extra={}){const s=new CloudStore({api,storage:memory(),online:()=>true,...extra});await s.setUser({id:'family'});return s;}
async function started(api,extra){const s=await store(api,extra);await s.replace(fresh(),{initial:true});await s.change(hatch);return s;}
test('initial migration is explicit and old local data is retained',async()=>{const storage=memory(),old=fresh();hatch(old);storage.setItem('eileen-magic-pets-v1',JSON.stringify(old));const s=await store(backend(),{storage});assert.equal(s.row,null);assert.equal(s.state.pets.length,0);await s.replace(s.legacy,{initial:true});assert.equal(s.state.pets.length,1);assert.equal(storage.getItem('eileen-magic-pets-v1'),JSON.stringify(old));});
test('two devices cannot spend the same star; loser refreshes',async()=>{const api=backend(),a=await started(api);await a.change(s=>lesson(s,'one'));const b=await store(api);await a.change(s=>equip(s,'clothes','mint-top'));await assert.rejects(()=>b.change(s=>equip(s,'clothes','pink-top')),/其他设备/);assert.equal(b.state.stars,0);assert.deepEqual(b.state.owned,a.state.owned);});
test('lost response retries same operation id exactly once',async()=>{const base=backend();let lose=true;const api={...base,commit:async p=>{const row=await base.commit(p);if(lose){lose=false;throw Error('lost response');}return row;}};const s=await store(api);await s.replace(fresh(),{initial:true});assert.equal(s.row.revision,1);assert.equal((await api.history()).length,1);});
test('unknown result blocks writes until same receipt is reconciled',async()=>{const base=backend();let fail=false;const api={...base,commit:async p=>{const result=await base.commit(p);if(fail)throw Error('timeout');return result;}};const s=await started(api);fail=true;await assert.rejects(()=>s.change(x=>lesson(x,'one')),/核对/);assert.equal(s.canWrite,false);assert.equal(s.state.stars,0);fail=false;await s.refresh();assert.equal(s.state.stars,1);assert.equal(s.pending,null);assert.equal(s.row.revision,3);});
test('offline and service pause preserve cache and reject writes',async()=>{let online=true;const s=await started(backend(),{online:()=>online});online=false;s.disconnected();await assert.rejects(()=>s.change(hatch));assert.equal(s.state.pets.length,1);online=true;s.api.read=async()=>{throw Error('paused');};await s.refresh();assert.equal(s.canWrite,false);assert.equal(s.state.pets.length,1);});
test('logout hides data; fresh login restores account cache only',async()=>{const api=backend(),s=await started(api);await s.setUser(null);assert.equal(s.state.pets.length,0);assert.equal(s.canWrite,false);await s.setUser({id:'family'});assert.equal(s.state.pets.length,1);s.api.read=async()=>{throw Error('offline');};await s.setUser({id:'other'});assert.equal(s.state.pets.length,0);});
test('writes do not mutate visible state until server acknowledges; simultaneous local writes rejected',async()=>{const base=backend(),s=await started(base);let resolve;const commit=base.commit;s.api={...base,commit:async p=>{await new Promise(r=>resolve=r);return commit(p);}};const first=s.change(x=>lesson(x,'one'));await Promise.resolve();assert.equal(s.state.stars,0);await assert.rejects(()=>s.change(x=>lesson(x,'two')));resolve();await first;assert.equal(s.state.stars,1);});
test('late response after logout cannot expose previous account data',async()=>{const base=backend(),s=await started(base);let resolve;s.api={...base,read:()=>new Promise(r=>resolve=r)};const pending=s.refresh();await s.setUser(null);resolve(await base.read());await pending;assert.equal(s.state.pets.length,0);});
test('history limited to twenty snapshots; restoring creates a new revision',async()=>{const s=await started(backend());const old=structuredClone(s.state);for(let i=0;i<25;i++)await s.change(x=>lesson(x,String(i)));const rev=s.row.revision;await s.replace(old);const history=await s.history();assert.equal(history.length,20);assert.equal(s.row.revision,rev+1);assert.equal(history[1].state.lessons.length,25);});
test('strict import rejects malformed states, bad references and injected markup',()=>{const s=fresh();hatch(s);for(const mutate of [x=>x.stars=-1,x=>x.pets[0].name='<img>',x=>x.selected='missing',x=>x.pets[0].outfit.hand='mint-top',x=>x.routes.out=[[1]],x=>x.hatched=9,x=>x.pets[0].outfit.decor='rainbow']){const bad=structuredClone(s);mutate(bad);assert.throws(()=>validateSave(bad));}assert.throws(()=>parseBackup('{broken'));assert.deepEqual(parseBackup(backupText(s)),s);});
test('validation never silently completes an offline trip',()=>{const s=fresh();hatch(s);travel(s,0);assert.deepEqual(parseBackup(backupText(s)),s);});
