import {KEY,SPECIES,ITEMS,PRIZES,fresh,current,level,adult,hatch,lesson,draw,equip,collect,feed,saveRoute,travel,arrive,restore} from './game.js';
import {petArt,eggArt,mapArt} from './art.js';
import {setupParent,verifyParent} from './parent.js';
import {CloudStore} from './cloud-store.js';
import {api,client} from './supabase.js';
import {createSettings} from './settings.js';
const $=s=>document.querySelector(s);
const store=new CloudStore({api,onChange:()=>{state=store.state;render();}});
let state=store.state;
let tab='home',category='clothes',routeDir='out',editing=false,draft=[],toastTimer,modalOpener;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const layer=document.createElement('div');layer.className='celebration';layer.setAttribute('aria-hidden','true');layer.innerHTML=Array.from({length:24},(_,i)=>`<i style="--x:${Math.random()*100}vw;--delay:${Math.random()*.35}s;--color:${['#d995ae','#e8c565','#adc4a0','#c1aed7'][i%4]};--turn:${Math.random()*720}deg">${i%3?'✦':'♡'}</i>`).join('');document.body.append(layer);setTimeout(()=>layer.remove(),2200);}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
async function act(fn,message){try{const selected=state.selected;const value=await store.change(s=>{if(s.pets.some(p=>p.id===selected))s.selected=selected;return fn(s);});if(message){toast(message);if(/咔嚓|你好呀|收好啦|变漂亮/.test(message))celebrate();}return {value};}catch(e){toast(e.message);return null;}}
const navs=[['home','⌂','宠物小屋'],['wardrobe','♧','魔法衣橱'],['zoo','♧','森林动物园'],['nursery','♧','魔法孵化屋']];
function render(){const p=current(state);$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#" aria-label="宠物小屋"><span class="brand-icon">✦</span><span>魔法宠物屋<small>EILEEN’S LITTLE WORLD</small></span></a><div class="sidebar-label">我的小小世界</div><nav>${navs.map(([id,icon,label],i)=>`<button class="nav ${tab===id?'active':''}" data-tab="${id}" aria-current="${tab===id?'page':'false'}"><span>${['⌂','♧','♧','♧'][i]}</span>${label}${id==='nursery'&&state.eggs?`<b>${state.eggs}</b>`:''}</button>`).join('')}</nav><div class="side-note"><span>✧</span><p>每一点努力，<br>都会长出小小的魔法。</p><div>慢慢学，一起长大</div></div><div class="profile"><span>E</span><div>Eileen 的成长花园<small>● ${esc(store.status)}</small></div></div></aside><main><header><div class="breadcrumb">我的小小世界 <span>/</span> ${navs.find(n=>n[0]===tab)[2]}</div><div class="balances"><span title="可用于兑换装扮">✦ <b>${state.stars}</b> 星星</span><span title="学完一课获得一次抽奖机会">♧ <b>${state.tickets}</b> 抽奖机会</span></div></header><div class="page"><div class="cloud-bar"><span role="status">${esc(store.busy?'正在核对云存档…':store.status)}${store.cacheWarning?' · 本机缓存失败，请导出备份':''}</span><button class="secondary" data-action="settings">⚙ 家长设置</button></div><div class="page-heading"><div><div class="eyebrow">A LITTLE LEARNING, A LITTLE MAGIC</div><h1>${{home:'今天，也一起长大吧',wardrobe:'给可爱，再加一点魔法',zoo:'去森林里，撒个欢吧',nursery:'一颗蛋，一个新朋友'}[tab]}<span class="heading-star">✧</span></h1><p>${{home:'欢迎回来，Eileen！你的小伙伴正在等你一起创造新故事。',wardrobe:'挑一件喜欢的装扮，让小伙伴闪闪发光。',zoo:'画下自己的小路，带小伙伴去看看更大的世界。',nursery:'陪一个宝宝长大，再迎接下一个小生命。'}[tab]}</p></div><button class="primary learn" data-action="lesson">♧ 请家长确认一课</button></div>${tab==='home'?home(p):tab==='wardrobe'?wardrobe(p):tab==='zoo'?zoo(p):nursery(p)}<footer><span>✦ 为每一次小小的进步施个魔法</span><button data-action="rules">玩法与成长规则</button></footer></div></main>`;
 bind();if(!store.canWrite||!store.row){document.querySelectorAll('[data-equip],[data-species],[data-action]').forEach(b=>{if(!['settings','rules','cancel-route'].includes(b.dataset.action))b.disabled=true;});}if(state.trip)animateTrip();}
function petSelect(){return state.pets.length?`<div class="pet-select">${state.pets.map(p=>`<button data-pet="${p.id}" class="${p.id===state.selected?'selected':''}">${SPECIES.find(s=>s.id===p.species).label} · ${p.name}<span>Lv.${level(p)}</span></button>`).join('')}</div>`:'';}
function room(p,large=false){return `<div class="room ${large?'large':''}"><div class="room-window"><i></i></div><div class="wall-stars">✧<span>✦</span>✧</div><div class="room-plant">♧</div><div class="rug"></div>${p?`<span class="room-tag">${p.location==='zoo'?'森林里的小屋':'温暖的小家'} · 第 ${p.generation} 代</span><div class="pet-stage">${petArt(p)}</div>${p.outfit.decor?`<div class="decoration" title="${PRIZES.find(i=>i.id===p.outfit.decor).name}">${PRIZES.find(i=>i.id===p.outfit.decor).icon}</div>`:''}<span class="speech">${state.trip?.pet===p.id?'正在去冒险的路上…':p.location==='zoo'?'森林里的风好舒服呀！':'今天也想和你一起学习！'}</span>`:`<span class="room-tag">你的第一位魔法伙伴</span><button class="egg-button" data-action="hatch-first" aria-label="孵化第一只小猫">${eggArt()}</button><span class="speech">咚咚！里面住着一只小猫哦</span>`}</div>`;}
function home(p){return `${petSelect()}<div class="home-grid"><section class="card pet-card"><div class="section-title"><h2>${p?`${p.name}的小屋`:'一位新朋友，正在等你'}</h2><span class="pill">${p?adult(p)?'✦ 已成年':level(p)===2?'✦ 正在长大':'✦ 魔法宝宝':'✦ 故事的开始'}</span></div>${room(p,true)}${p?`<div class="pet-info"><div><h3>${p.name}<span>Lv.${level(p)}</span></h3><p>${SPECIES.find(s=>s.id===p.species).label} · ${adult(p)?'已经长成闪闪发光的大朋友':'每学一课，就长大一点点'}</p></div><div class="points"><b>${p.points}</b><span>成长分</span></div></div><div class="progress"><i style="width:${Math.min(p.points/5*100,100)}%"></i></div><div class="progress-label"><span>${adult(p)?'已经成年 · 可以孕育魔法蛋':`距离成年还差 ${5-p.points} 课`}</span><span>${Math.min(p.points,5)} / 5 课</span></div><div class="room-actions"><button data-tab="wardrobe">♧ 换个新装扮</button><button data-tab="zoo">♧ ${p.location==='zoo'?'去动物园看看':'去动物园玩'}</button></div>`:`<div class="welcome-egg"><h3>从一颗魔法蛋开始</h3><p>轻轻点一下，遇见拿着魔法棒的小猫。</p><button class="primary" data-action="hatch-first">✧ 孵化我的小猫</button></div>`}</section><div class="right-stack"><section class="lesson-card"><span class="small-label">学习的魔法</span><div class="book-art">📖<span>✦</span></div><h2>每学一课，<br>都有一点新惊喜。</h2><p>在学习机 Pad 上完成一课，请家长来施个魔法。</p><div class="rewards"><span>✦<b>1</b>成长分</span><span>✧<b>1</b>兑换星星</span><span>♧<b>1</b>抽奖机会</span></div><button class="primary" data-action="lesson">请家长确认，领取奖励 <span>↗</span></button><small>在学习机 Pad 上学完一课，由家长输入密码确认</small></section><section class="card lottery-card"><div class="gift-art">🎁</div><div><h2>拆一份魔法惊喜</h2><p>漂亮裙子、可爱摆件，等你发现。</p><button class="text-button" data-action="draw" ${state.tickets?'':'disabled'}>${state.tickets?`抽一份礼物 · 剩余 ${state.tickets} 次 →`:'学完一课，获得抽奖机会'}</button></div></section><section class="card tiny-progress"><span class="sun-icon">☀</span><div><h3>小小努力，被好好记住</h3><p>已经完成 <b>${state.lessons.length}</b> 课，遇见 <b>${state.pets.length}</b> 位伙伴</p></div></section></div></div><div class="bottom-grid"><section class="card journal"><div class="section-title"><h2>成长的小脚印</h2><span class="muted">每一课都算数</span></div>${state.lessons.length?state.lessons.slice(-3).reverse().map(l=>`<div class="journal-row"><span class="journal-dot">✓</span><div><b>${esc(l.title)}</b><small>${new Date(l.date).toLocaleDateString('zh-CN')} · ${state.pets.find(p=>p.id===l.pet)?.name}获得 1 成长分</small></div><em>＋1 ✦</em></div>`).join(''):'<div class="empty-journal">✎ <span>在学习机上完成一课，请家长点亮第一枚脚印。</span></div>'}</section><section class="next-chapter"><span>THE NEXT LITTLE CHAPTER</span><h2>${p?.eggReady?'新的魔法蛋，准备好啦！':'长大的魔法，还在继续'}</h2><p>${p?.eggReady?'收集魔法蛋，迎接下一位小伙伴。':'宝宝 → 成长 → 成年 → 孕育新的魔法蛋'}</p><button class="text-button" data-tab="nursery">去魔法孵化屋看看 →</button><div class="chapter-egg">🥚</div></section></div>`;}
function wardrobe(p){if(!p)return needPet();let items=category==='dress'?PRIZES.filter(i=>i.kind==='dress'):category==='decor'?PRIZES.filter(i=>i.kind==='decor'):ITEMS[category];const cats=[['clothes','衣服'],['bracelet','手镯'],['clip','发卡'],['hand','手持物'],['makeup','化妆'],['dress','抽奖裙子'],['decor','小装饰']];return `${petSelect()}<div class="wardrobe-grid"><section class="card"><div class="section-title"><h2>${p.name}的试衣间</h2><span class="pill">Lv.${level(p)}</span></div>${room(p)}<div class="wardrobe-hint">✧ ${p.name}说：“我变漂亮啦！”</div><button class="secondary reset-outfit" data-action="reset-outfit">卸下装扮</button></section><section class="card closet"><h2>今天想穿什么呢？</h2><p class="muted">普通装扮每件 1 星星，兑换后可以一直穿。</p><div class="category-tabs" role="tablist">${cats.map(([id,label])=>`<button role="tab" aria-selected="${category===id}" data-category="${id}" class="${category===id?'active':''}">${label}</button>`).join('')}</div><div class="item-grid">${items.map(i=>{let owned=state.owned.includes(i.id),worn=Object.values(p.outfit).includes(i.id);return `<button class="item ${worn?'worn':''}" data-equip="${i.id}" ${!owned&&(i.kind==='dress'||i.kind==='decor')?'disabled':''}><span class="item-picture" style="--item-color:${i.color||'#bad0ba'}">${itemIcon(i,category)}</span><b>${i.name}</b><small>${worn?'✓ 正在穿戴':owned?'已拥有 · 点击换上':i.kind==='dress'||i.kind==='decor'?'仅抽奖获得':`✦ ${i.cost} 星星兑换`}</small></button>`;}).join('')}</div><div class="closet-note">🎁 裙子和小摆件藏在魔法礼物里。<button class="text-button" data-action="draw" ${state.tickets?'':'disabled'}>抽一份礼物（${state.tickets}）→</button></div></section></div>`;}
function itemIcon(i,c){if(i.kind==='decor')return i.icon;if(i.kind==='dress')return `<svg viewBox="0 0 80 80"><path d="M28 13 L52 13 54 30 70 66 Q40 80 10 66 L26 30Z" fill="${i.color}"/><path d="M27 31H54" stroke="#fff8e8" stroke-width="5"/><path d="M40 46 l3 6 7 1 -5 5 1 7 -6 -4 -6 4 1 -7 -5 -5 7 -1Z" fill="#fff0cb"/></svg>`;return {clothes:i.kind==='bottom'?'👖':'👕',bracelet:'◌',clip:i.id==='bow'?'🎀':'🌼',hand:i.id==='wand'?'🪄':'💗',makeup:i.id==='blush'?'🌸':'✨'}[c]||'✧';}
function needPet(){return `<section class="card empty-state">${eggArt()}<h2>先叫醒蛋里的小伙伴吧</h2><p>孵化你的第一只小猫，就可以开始新的故事。</p><button class="primary" data-action="hatch-first">孵化第一只小猫</button></section>`;}
function nursery(p){const can=state.pets.every(adult);return `${petSelect()}<div class="nursery-grid"><section class="card hatch-card"><span class="pill">魔法蛋篮 · ${state.eggs} 颗</span>${eggArt()}<h2>${state.pets.length?'每一个新生命，都值得期待':'第一颗蛋里，是拿魔法棒的小猫'}</h2><p>${can?'选一位小伙伴，轻轻唤醒它。':'先陪现在的宝宝获得 5 次学习奖励，再迎接下一位。'}</p><div class="species-grid">${SPECIES.map((sp,i)=>`<button data-species="${sp.id}" ${!state.eggs||!can||!state.hatched&&i>0?'disabled':''}><span>${['🐱','🐶','🐰','🐻','🐹','🦊','🐥','🐹','🐦','🐢'][i]}</span>${sp.label}</button>`).join('')}</div></section><div><section class="card egg-status"><h2>长大后的小小魔法</h2><p>获得家长确认的 5 课奖励后成年，获得第一颗魔法蛋。<br>收蛋后，再陪成年宠物学 3 课，它会孕育下一颗。</p>${p?`${petArt(p,{mini:true})}<h3>${p.name} · ${adult(p)?'已成年':'还在长大'}</h3><p>${p.eggReady?'一颗新的魔法蛋已经准备好啦！':adult(p)?`下一颗蛋：${p.eggProgress} / 3 课`:`距离成年：还差 ${5-p.points} 课`}</p><button class="primary" data-action="collect" ${p.eggReady?'':'disabled'}>${p.eggReady?'收集魔法蛋 ＋1':'耐心陪伴，慢慢长大'}</button>`:''}</section><div class="family-note">♡ 已经长大的小伙伴会一直留在这里。<br>新宝宝也会长大，继续孕育新的魔法蛋。</div></div></div>`;}
function zoo(p){if(!p)return needPet();const route=editing?draft:state.routes[routeDir];return `${petSelect()}<section class="card zoo-card"><div class="section-title"><div><h2>森林动物园</h2><p class="muted">${editing?'点击地图添加途经点，起点和终点会自动连好。':'小伙伴可以来游玩，也可以住下来；想家时随时接回。'}</p></div><span class="pill">${state.trip?.pet===p.id?'正在路上…':p.location==='zoo'?'♧ 在动物园':'⌂ 在家里'}</span></div><div class="route-toolbar"><div class="segmented"><button data-direction="out" class="${routeDir==='out'?'active':''}">去动物园的小路</button><button data-direction="back" class="${routeDir==='back'?'active':''}">回家的小路</button></div><div>${editing?'<button class="secondary" data-action="undo-route">撤销一点</button><button class="primary" data-action="save-route">保存路线</button><button class="text-button" data-action="cancel-route">取消</button>':'<button class="secondary" data-action="edit-route">✎ 设计这条路线</button>'}</div></div><div id="zoo-map" class="zoo-map ${editing?'editing':''}">${mapArt()}<div class="map-label home-label">🏡<b>温暖的小家</b></div><div class="map-label zoo-label">🎪<b>森林动物园</b></div><div class="map-tree">🌲</div><div class="map-flower">🌷</div><svg class="route-svg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points="${route.map(x=>x.join(',')).join(' ')}"/><g>${route.slice(1,-1).map(([x,y])=>`<circle cx="${x}" cy="${y}" r="1"/>`).join('')}</g></svg><div id="traveler" style="left:${p.location==='home'?10:90}%;top:${p.location==='home'?72:25}%">${petArt(p,{mini:true})}</div><span class="map-caption">${editing?'✎ 点一点，画出属于你的小路':'✧ 沿着你画的小路，出发吧'}</span></div><div class="zoo-actions"><div><h3>${state.trip?.pet===p.id?`${p.name}正在散步`:p.location==='zoo'?`${p.name}正在享受森林时光`:`${p.name}准备好出门啦`}</h3><p>${p.location==='zoo'?`已经喂食 ${p.food} 次 · 可以一直住着，也可以随时回家`:'去程和回程可以走不同的小路哦'}</p></div><div><button class="secondary" data-action="feed" ${p.location!=='zoo'||state.trip?.pet===p.id?'disabled':''}>🥕 喂一份点心</button><button class="primary" data-action="travel" ${state.trip||editing?'disabled':''}>${state.trip?'正在路上…':p.location==='home'?'送去动物园 →':'接回家 →'}</button></div></div></section>`;}
function showModal(html){modalOpener=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="close" aria-label="关闭">×</button>${html}</section></div>`;$('.close').onclick=closeModal;$('.modal-backdrop').onclick=e=>{if(e.target===$('.modal-backdrop'))closeModal();};requestAnimationFrame(()=>($('.modal input')||$('.modal .primary')||$('.close')).focus());}
function closeModal(){$('#modal-root').innerHTML='';if(modalOpener?.isConnected)modalOpener.focus();else $('.learn')?.focus();}
function lessonModal(){
 if(!current(state)){toast('先孵化你的魔法小猫，再请家长确认学习奖励吧。');return;}
 const first=!state.parentAuth;
 showModal(`<span class="modal-symbol">♧</span><h2 id="modal-title">${first?'请家长先设置确认密码':'请家长确认学习完成'}</h2><p>${first?'这一步请交给家长。设置后，每次发放奖励都需要输入密码。':'请在另一台学习机 Pad 上检查孩子确实已完成这一课，再输入家长密码。'}</p><form id="lesson-form">${first?'':`<label for="lesson-name">已在学习机 Pad 上完成的课程</label><input id="lesson-name" maxlength="60" required placeholder="例如：语文第 1 课 · 秋天">`}<label for="parent-pin">${first?'设置家长密码（4–6 位数字）':'家长密码'}</label><input id="parent-pin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" required autocomplete="off" placeholder="请家长输入，勿告诉孩子">${first?'<label for="confirm-pin">再次输入密码</label><input id="confirm-pin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" required autocomplete="off">':`<div class="modal-reward">给 ${current(state).name} ＋1 成长分 · ＋1 星星 · ＋1 抽奖机会</div><label class="confirm-check"><input id="parent-confirm" type="checkbox" required> 我已检查 Pad，确认这一课完成且尚未领过奖励</label>`}<p id="parent-error" role="alert" class="parent-error"></p><button class="primary" type="submit">${first?'保存家长密码':'家长确认完成，发放这一课奖励'}</button><small>${first?'请家长妥善记住密码。设置密码本身不会发放奖励。':'每次仅发放一课奖励；本游戏不会自动读取学习机。'}</small></form>`);
 let busy=false;
 $('#lesson-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const submit=e.currentTarget.querySelector('button[type=submit]');submit.disabled=true;const pin=$('#parent-pin').value;const error=$('#parent-error');
 try{let failure;
 const title=first?'':$('#lesson-name').value.trim(),confirm=first?$('#confirm-pin').value:'';
 const selected=state.selected;
 await store.change(async s=>{
  if(s.pets.some(p=>p.id===selected))s.selected=selected;
  if(first){s.parentAuth=await setupParent(pin,confirm);return;}
  if(!title)throw Error('请填写已在 Pad 上完成的课程。');
  try{await verifyParent(s.parentAuth,pin);}catch(e){failure=e;return;}
  lesson(s,title);
 });
 if(failure)throw failure;
 closeModal();toast(first?'家长密码已保存。':'家长已确认！成长分、星星和抽奖机会各 ＋1');if(!first)celebrate();
 }catch(e){error.textContent=e.message;submit.disabled=false;busy=false;}
 };
}
async function lottery(){if(!state.tickets){toast('学完一课，就有一次抽奖机会哦。');return;}const saved=await act(s=>draw(s));if(!saved)return;const prize=saved.value;celebrate();showModal(`<span class="modal-symbol prize-icon">${itemIcon(prize,'dress')}</span><div class="eyebrow">A LITTLE SURPRISE FOR YOU</div><h2 id="modal-title">收到${prize.name}啦！</h2><p>${prize.kind==='dress'?'漂亮的裙子，是认真学习的小惊喜。':'放在小伙伴身旁，让小家更温暖。'}</p><p class="muted">已放进衣橱 · 剩余 ${state.tickets} 次抽奖机会</p><button class="primary" id="wear-prize">现在就${prize.kind==='dress'?'穿上':'摆好'}</button>`);$('#wear-prize').onclick=()=>{act(s=>equip(s,prize.kind,prize.id),'我变漂亮啦 ✨');closeModal();};}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;editing=false;render();});document.querySelectorAll('[data-pet]').forEach(b=>b.onclick=()=>{state={...store.state,selected:b.dataset.pet};editing=false;render();});document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;render();});document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>act(s=>equip(s,category,b.dataset.equip),'我变漂亮啦 ✨'));document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>act(s=>{hatch(s,b.dataset.species);tab='home';},'咔嚓！欢迎新的魔法小伙伴 ♡'));document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>{routeDir=b.dataset.direction;editing=false;render();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));$('.brand').onclick=e=>{e.preventDefault();tab='home';render();};if(editing)$('#zoo-map').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();if(draft.length>=14){toast('这条小路最多可以放 12 个途经点。');return;}draft.splice(-1,0,[(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100]);render();};}
function action(a){if(a==='settings'){openSettings();return;}if(!['rules','cancel-route'].includes(a)&&(!store.canWrite||!store.row)){toast('请在家长设置中连接云存档。');return;}switch(a){case'lesson':lessonModal();break;case'hatch-first':act(s=>hatch(s),'你好呀，奶糖！魔法故事开始啦 ♡');break;case'draw':lottery();break;case'collect':act(s=>collect(s),'收好啦！魔法蛋篮 ＋1');break;case'feed':act(s=>feed(s),'啊呜！好好吃，谢谢你 ♡');break;case'travel':act(s=>{travel(s);routeDir=s.trip.direction;},'沿着你设计的小路，出发！');break;case'edit-route':editing=true;draft=[state.routes[routeDir][0],state.routes[routeDir].at(-1)].map(x=>[...x]);render();break;case'undo-route':if(draft.length>2)draft.splice(-2,1);render();break;case'save-route':act(s=>{saveRoute(s,routeDir,draft);editing=false;},'这条专属小路保存好啦');break;case'cancel-route':editing=false;render();break;case'reset-outfit':act(s=>current(s).outfit={},'装扮已收回衣橱');break;case'rules':showModal(`<span class="modal-symbol">✦</span><h2 id="modal-title">小小的魔法规则</h2><ul class="rules"><li>孩子在另一台学习机 Pad 上学完一课，家长检查后输入密码确认：当前宠物 ＋1 成长分、账户 ＋1 星星、＋1 次抽奖。孩子不能自行领取奖励。</li><li>0–1 分是 Lv.1 宝宝，2–4 分是 Lv.2，5 分起是 Lv.3 成年。成长分不会因兑换减少。</li><li>普通装扮 1 星星一件，魔法棒免费。兑换后所有宠物都能用，上衣与裤子可以搭配，裙子会替换上衣和裤子。裙子和摆件只能抽奖；每次消耗 1 次机会，优先抽未拥有的礼物。</li><li>成年时准备第一颗魔法蛋；收蛋后，当前成年宠物再学 3 课可产下一颗。蛋准备好时等你收取，不累积多颗。</li><li>一个宝宝长大后，才可孵化下一只。已养成的宠物全部保留。</li><li>在动物园可反复喂食、长期住下、随时回家。喂食不增加学习奖励。</li><li>进度联网保存到家庭云存档。断网只能查看缓存；新设备由家长登录后恢复。</li></ul>`);break;}}
let frame;
function animateTrip(){cancelAnimationFrame(frame);if(!state.trip)return;const t=state.trip;function tick(){if(!state.trip)return;if(Date.now()>=t.start+t.duration){if(store.canWrite)act(s=>arrive(s),'到达啦！');return;}const el=$('#traveler');if(el&&current(state)?.id===t.pet){const progress=Math.min(1,(Date.now()-t.start)/t.duration),pts=t.points,lengths=pts.slice(1).map((p,i)=>Math.hypot(p[0]-pts[i][0],p[1]-pts[i][1])),total=lengths.reduce((a,b)=>a+b,0);let distance=total*progress,i=0;while(i<lengths.length-1&&distance>lengths[i]){distance-=lengths[i];i++;}const f=lengths[i]?distance/lengths[i]:0;el.style.left=pts[i][0]+(pts[i+1][0]-pts[i][0])*f+'%';el.style.top=pts[i][1]+(pts[i+1][1]-pts[i][1])*f+'%';}frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);}
const openSettings=createSettings({store,client,showModal,closeModal,toast,esc});
window.addEventListener('offline',()=>store.disconnected());
window.addEventListener('online',()=>store.refresh());
window.addEventListener('focus',()=>store.refresh());
window.addEventListener('storage',e=>{if(e.key?.startsWith('eileen-cloud-v1:'))store.refresh();});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)store.refresh();});
setInterval(()=>{if(!document.hidden)store.refresh();},15000);
if(client){
 client.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>{if(store.user?.id!==session?.user?.id)closeModal();store.setUser(session?.user||null);},0);});
 client.auth.getSession().then(({data,error})=>{if(error){store.disconnected();return;}store.setUser(data.session?.user||null);});
}
document.addEventListener('keydown',e=>{if(!$('.modal'))return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const els=[...$('.modal').querySelectorAll('button,input')].filter(x=>!x.disabled);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
render();
